spring:
   profiles:
      active:
        - dev
---
server:
  port: 8201

spring:
  profiles: dev
  application:
      name: microconfig-test-client222

eureka:
 client:
  service-url:
    defaultZone: http://admin:a@localhost:7002/eureka
info:
  app.name: microservice-config-client-dev
  company.name: yc
---
server:
  port: 8102

spring:
  profiles: beta
  application:
      name: microconfig-test-client333

eureka:
 client:
  service-url:
    defaultZone: http://admin:a@localhost:7003/eureka
    
info:
  app.name: microservice-config-client-beta
  company.name: hyycinfo
